# Generated by Django 5.1.7 on 2025-03-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_pedido_total_curso01_pedido_total_curso02_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='datanasc',
        ),
        migrations.AddField(
            model_name='cliente',
            name='contato',
            field=models.CharField(default='(86)90000-0000', max_length=14, verbose_name='contato'),
            preserve_default=False,
        ),
    ]
