# Generated by Django 5.1.7 on 2025-03-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_cliente_datanasc_cliente_contato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='contato',
            field=models.CharField(max_length=15, verbose_name='Contato'),
        ),
    ]
