# Generated by Django 5.1.7 on 2025-03-20 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_cliente_contato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='qtde',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
