# Generated by Django 5.1.7 on 2025-03-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_itempedido_qtde'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='qtde',
            field=models.PositiveIntegerField(),
        ),
    ]
