# Generated by Django 5.1.7 on 2025-03-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_itempedido_qtde'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='total_curso06',
            field=models.IntegerField(null=True),
        ),
    ]
