# Generated by Django 5.1.7 on 2025-04-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_pedido_total_curso06'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='total_alunos',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='contato',
            field=models.CharField(max_length=20, verbose_name='Contato'),
        ),
    ]
